Document: selinuxpack
Title: Debian selinuxpack Manual
Author: <insert document author here>
Abstract: This manual describes what selinuxpack is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/selinuxpack/selinuxpack.sgml.gz

Format: postscript
Files: /usr/share/doc/selinuxpack/selinuxpack.ps.gz

Format: text
Files: /usr/share/doc/selinuxpack/selinuxpack.text.gz

Format: HTML
Index: /usr/share/doc/selinuxpack/html/index.html
Files: /usr/share/doc/selinuxpack/html/*.html
