Document: refpolicypk
Title: Debian refpolicypk Manual
Author: <insert document author here>
Abstract: This manual describes what refpolicypk is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/refpolicypk/refpolicypk.sgml.gz

Format: postscript
Files: /usr/share/doc/refpolicypk/refpolicypk.ps.gz

Format: text
Files: /usr/share/doc/refpolicypk/refpolicypk.text.gz

Format: HTML
Index: /usr/share/doc/refpolicypk/html/index.html
Files: /usr/share/doc/refpolicypk/html/*.html
